### ISSUE TITLE
Installation error on print command syntax. (calibre 5.7.0)

### ISSUE THREAD

**Issue by brianscottwilson** [jdanders/calibre-plugin-language-cleaner#2]
When trying to install the Language Cleaner plugin the following error results.  I would be willing to assist in correcting the issue as this seems to be a simple syntax change.

calibre, version 5.7.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "calibre\gui2\dialogs\plugin_updater.py", line 709, in _install_clicked
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.language_clean_plugin.__init__", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.language_clean_plugin.cleaner", line 39
    print "*"*60, "sub=", sub, "val=", val, "*"*60
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("*"*60, "sub=", sub, "val=", val, "*"*60)?

**Comment by jdanders** [comment]
This has been fixed in the latest version. 

https://github.com/jdanders/calibre-plugin-language-cleaner/releases/tag/2020.09.07

**Comment by brianscottwilson** [comment]
The latest release for installation is 2019.9.2.  This version generated the error message I reported.  I see there have been additional changes applied to the master branch, but no way to get any newer version installed via the normal means.

**Comment by jdanders** [comment]
That's right -- I forgot. I emailed the maintainers of the plugin forum, but no one responded so the official one is old. If you download the zip I linked above and install that, it will work just fine.

**Comment by brianscottwilson** [comment]
I was able to find the current zip file and install it.  Unfortunately, the first time I saw the zip file, the page layout lead me to believe the zip was the 2019 version.  It wasn't until I took a very close look that I realized the zip was updated.

Thanks for the additional information though.  It was a big help.  If you need help with future coding help, I would be happy to help.

**Comment by jdanders** [comment]
Thanks for the reminder, hopefully the official update channel will have the update now!
